# -*- mode: python -*-

Import("env")

env.Library(target='unicode_utils', 
			source=[
				'u_string.cpp', 
				'u_mappings.cpp'
			]
)

env.CppUnitTest(target='u_string_test',
                source=[
                	'u_string_test.cpp'
                ],
                LIBDEPS=[
                	'unicode_utils', 
                	'$BUILD_DIR/mongo/unittest/unittest'
                ]
)
